if(!window.console){var console=function(){}}
var Application={wait_timer:{},required:{},actions:{},status:{},documentReady:!1,baseURL:function(){var s=this.appSourcePath;return(s.charAt(s.length-1)==='/')?s:s+'/'},checkObjects:function(objects){for(var i in objects){if(!window[objects[i]]){return !1;if(i!='$'){if(!this.documentReady){return !1}}}}
return !0},i:function(script){if(this.required[script]&&this.actions){for(var timerID in this.required[script]){if(this.actions[timerID]){this.w(this.actions[timerID].condition,this.actions[timerID].action,-1,timerID)}}}},cleanTimer:function(timerID){if(timerID&&this.wait_timer&&this.wait_timer[timerID]){clearTimeout(this.wait_timer[timerID]);this.wait_timer[timerID]=!1}},runSavedAction:function(timerID){this.actions[timerID].action();delete this.actions[timerID]},w:function(condition,action,wait,timerID){var that=this;var result=typeof condition==='function'?condition():this.checkObjects(condition);if(result){that.cleanTimer(timerID);if(typeof condition!=='function'&&timerID){for(var i in condition){if(that.required[condition[i]]&&that.required[condition[i]][timerID]){that.required[condition[i]][timerID]=!1}}
if(wait<0){}else{}
that.runSavedAction(timerID)}else{action()}}else{if(wait<0){return}
that.cleanTimer(timerID);if(!timerID){do{timerID=Math.round(Math.random()*10000)}while(that.wait_timer[timerID]);if(typeof condition!=='function'){for(var i in condition){if(!that.required[condition[i]]){that.required[condition[i]]={}}
that.required[condition[i]][timerID]=!0}}
that.actions[timerID]={action:action,condition:condition,wait:wait}}
that.wait_timer[timerID]=setTimeout(function(){that.w(condition,action,wait,timerID)},wait?wait:300)}},loadScript:function(path){},no:function(data){if(window.Preloader&&Preloader.hide)
Preloader.hide();var that=this;if(!data.action){this.w(['$','D','T'],function(){D.show({title:data.message?data.message:{error:{ru:'ОШИБКА',en:'ERROR'}},message:!1,css:that.getCss({type:'no'})})})}else{this.run(data.action)}},ok:function(data){for(var i in data){var toRun={};toRun[i]=data[i];this.run(toRun);}},run:function(data){var that=this;var r={};for(var field in data){if(typeof data[field]=='object'&&field!=0){if(window[field]){var Obj=window[field];for(var fn in data[field]){if(Obj[fn]&&(typeof Obj[fn]=='function')){if(fn=='getCss'){return Obj[fn](that.run(data[field][fn]))}else{r[field]=Obj[fn](that.run(data[field][fn]))}}}}else{r[field]=that.run(data[field])}}else{r[field]=data[field]}}
return r},css:{no:{dialog_back:{background:'black',opacity:0.7},message_back:{background:'rgb(242,30,34)',opacity:0.61},title:{color:'white'},message:{color:'white'},dialog_message:{border:'none'}},ok:{dialog_back:{background:'black',opacity:0.7},message_back:{background:'green',opacity:0.61},title:{color:'white'},message:{color:'white'},dialog_message:{border:'none'}},norm:{dialog_back:{background:'black',opacity:0.7},dialog_footer:{color:'white','text-align':'left','padding':'10px 15px','padding-top':'0px'},message_back:{background:'rgb(0, 138 ,180)',opacity:0.7},title:{color:'white'},message:{color:'white'},dialog_message:{border:'none'}}},getCss:function(input){return this.get_css(input)},get_css:function(input){if(!$('.dialog').length&&window.BOOTSTRAP_loaded){var aliaces={no:'type-danger',ok:'type-success',norm:'type-primary',info:'type-info',warning:'type-warning',white:'type-deafult'};return typeof input=='object'?(aliaces[input.type]?aliaces[input.type]:BootstrapDialog.TYPE_DEFAULT):(aliaces[input]?aliaces[input]:BootstrapDialog.TYPE_DEFAULT)}else{return this.css[input.type]}}};var A=Application;A.baseUrl='//crowdescrow.biz/';A.appSourcePath='//crowdescrow.biz/';A.appPath='https://apps.facebook.com/escrow';A.vh2015='/home/crowdesc/public_html/vendor/vh2016/';A.vh2015url='//crowdescrow.biz/vendor/vh2016/';A.w(['$','B','T'],function(){B._sid='889434c53a9f3bb5f0a3c59eb52ae326';T.locale='en';T.locales={"en":"English","ru":"\u0420\u0443\u0441\u0441\u043a\u0438\u0439"};APPLICATIONSETTINGSREADY=!0})